"""PII gate for the public tree and the release artefacts (S9, design-e963c656f5 §4.5).

Blocking in CI next to gitleaks. It always looks for a checkout under a drive's Projects folder, and for the
maintainer's usernames, emails and names, which live OUTSIDE the tracked tree (qa report-bcef24a36a: a needle
spelled in a tracked file, even as a character class or built from parts, publishes it). They come from

* the `PII_NEEDLES` environment variable (CI: the repository secret of that name), else
* `.pii-needles.toml` at the repo root (gitignored: the maintainer's machine), shaped as
      usernames = ["..."]    # whole word, case-insensitive
      emails    = ["..."]
      names     = ["...", "..."]

With neither, the owner rules are off and the gate says so on stderr (a fork's pull request has no secrets).

    python .github/scripts/pii_gate.py                 scan every tracked file (git ls-files)
    python .github/scripts/pii_gate.py --dir dist/     scan a folder of release artefacts, inside
                                                       wheels/sdists/vsix (zip, tar.gz) too
    python .github/scripts/pii_gate.py --gitleaks-config .gitleaks.pii.toml
                                                       write a gitleaks config: .gitleaks.toml (inlined) plus
                                                       the same owner rules (CI runs gitleaks on it)
    --require-needles                                  exit 2 when no owner needles are configured
Exit 0 clean, 1 findings (one `path:line: rule: excerpt` line each), 2 usage.
"""
from __future__ import annotations

import argparse
import io
import os
import re
import subprocess
import sys
import tarfile
import tomllib
import zipfile
from pathlib import Path

_PROJ = "proj" + "ects"
_SEP = r"(?:\\\\|\\|/|%5c|%2f)+"
NEEDLES_FILE = ".pii-needles.toml"
NEEDLES_ENV = "PII_NEEDLES"
KINDS = ("usernames", "emails", "names")

PROJECTS_RULE = ("projects root",
                 re.compile(rf"(?:[a-z](?::|%3a){_SEP}|(?<![\w.])/[a-z]:?/){_PROJ}(?:{_SEP}|$)", re.I | re.M))


def load_needles(root: Path) -> dict[str, list[str]] | None:
    """The owner needles from PII_NEEDLES, else <root>/.pii-needles.toml; None when neither holds any."""
    text = os.environ.get(NEEDLES_ENV, "")
    if not text.strip():
        f = root / NEEDLES_FILE
        if not f.is_file():
            return None
        text = f.read_text(encoding="utf-8")
    data = tomllib.loads(text)
    unknown = set(data) - set(KINDS)
    if unknown:
        raise ValueError(f"unknown key(s) {sorted(unknown)} in the PII needles; expected {', '.join(KINDS)}")
    out = {k: [str(v).strip() for v in data.get(k, []) if str(v).strip()] for k in KINDS}
    return out if any(out.values()) else None


def _alt(words: list[str]) -> str:
    return "|".join(re.escape(w) for w in words)


def owner_rules(needles: dict[str, list[str]] | None) -> list[tuple[str, re.Pattern[str]]]:
    rules: list[tuple[str, re.Pattern[str]]] = []
    if not needles:
        return rules
    if needles["emails"]:
        rules.append(("owner email", re.compile(_alt(needles["emails"]), re.I)))
    if needles["usernames"]:
        rules.append(("owner username",
                      re.compile(rf"(?<![A-Za-z0-9])(?:{_alt(needles['usernames'])})(?![A-Za-z0-9])", re.I)))
    if needles["names"]:
        rules.append(("owner name", re.compile(rf"\b(?:{_alt(needles['names'])})\b", re.I)))
    return rules


def gitleaks_config(needles: dict[str, list[str]] | None, base: str) -> str:
    """The tracked config text `base` plus the owner rules (RE2: word boundaries, no lookaround).

    Inlined, not `[extend] path = ...`: gitleaks 8.30.1 drops an extended file's `[[allowlists]]`, so every
    token-shaped test fixture the tracked config allowlists came back as a leak (CI run 36323612069, 22 hits)."""
    out = ["# generated by .github/scripts/pii_gate.py --gitleaks-config; never commit it (it holds the needles)",
           "# the tracked .gitleaks.toml, verbatim:", base.rstrip("\n"), ""]
    shapes = (("usernames", "pii-owner-username", r"(?i)\b(?:{})\b"),
              ("emails", "pii-owner-email", r"(?i)(?:{})"),
              ("names", "pii-owner-name", r"(?i)\b(?:{})\b"))
    for kind, rid, shape in shapes:
        if needles and needles[kind]:
            regex = shape.format(_alt(needles[kind]))
            out += ["[[rules]]", f"id = '{rid}'", f"description = 'owner {kind} (from the PII needles)'",
                    "regex = '''" + regex + "'''", ""]
    return "\n".join(out)


#: what scan_text looks for; main() prepends the owner rules once the needles are loaded
RULES: list[tuple[str, re.Pattern[str]]] = [PROJECTS_RULE]
ARCHIVES = (".whl", ".zip", ".vsix")
TARS = (".tar.gz", ".tgz")


def scan_text(path: str, text: str) -> list[str]:
    hits = []
    for label, rx in RULES:
        for m in rx.finditer(text):
            line = text.count("\n", 0, m.start()) + 1
            hits.append(f"{path}:{line}: {label}: {text[max(0, m.start() - 20):m.end() + 20]!r}")
    return hits


def _decode(data: bytes) -> str | None:
    # The raw stream always. Whenever the stream holds a NUL ANYWHERE (not only in a prefix: adversary R2-D,
    # a UTF-16 string after 8 KiB of text was missed), the WHOLE stream again: with the NULs dropped, and
    # decoded as UTF-16LE and UTF-16BE at both byte alignments. The decodes keep a UTF-16 needle's neighbours
    # as the characters they really are (NUL-dropping alone glues ASCII bytes onto it and defeats the
    # username rule's boundary).
    if b"\0" not in data:
        return data.decode("utf-8", errors="replace")
    views = [data.decode("latin-1"), data.replace(b"\0", b"").decode("latin-1")]
    for enc in ("utf-16-le", "utf-16-be"):
        views += [data[i:].decode(enc, errors="replace") for i in (0, 1)]
    return "\n".join(views)


def scan_bytes(path: str, data: bytes) -> list[str]:
    low = path.lower()
    if low.endswith(ARCHIVES):
        hits = []
        with zipfile.ZipFile(io.BytesIO(data)) as z:
            for info in z.infolist():
                if not info.is_dir():
                    hits += scan_bytes(f"{path}!{info.filename}", z.read(info))
        return hits
    if low.endswith(TARS):
        hits = []
        with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as t:
            for m in t.getmembers():
                f = t.extractfile(m) if m.isfile() else None
                if f is not None:
                    hits += scan_bytes(f"{path}!{m.name}", f.read())
        return hits
    text = _decode(data)
    return scan_text(path, text) if text is not None else []


def tracked_files(root: Path) -> list[str]:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=root, capture_output=True, check=True).stdout
    return [p for p in out.decode("utf-8").split("\0") if p]


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dir", type=Path, help="scan this folder instead of the tracked tree")
    ap.add_argument("--root", type=Path, default=Path.cwd(), help="repo root (tracked-tree scan, .pii-needles.toml)")
    ap.add_argument("--gitleaks-config", type=Path, help="write a gitleaks config with the owner rules, then exit")
    ap.add_argument("--require-needles", action="store_true", help="exit 2 when no owner needles are configured")
    a = ap.parse_args(argv)
    try:
        needles = load_needles(a.root)
    except (ValueError, tomllib.TOMLDecodeError) as e:
        print(f"pii gate: bad PII needles: {e}", file=sys.stderr)
        return 2
    if needles is None:
        print(f"pii gate: no owner needles ({NEEDLES_ENV} unset, no {NEEDLES_FILE}): the owner rules are OFF",
              file=sys.stderr)
        if a.require_needles:
            return 2
    RULES[:] = [*owner_rules(needles), PROJECTS_RULE]
    if a.gitleaks_config:
        base = (a.root / ".gitleaks.toml").read_text(encoding="utf-8")
        a.gitleaks_config.write_text(gitleaks_config(needles, base), encoding="utf-8")
        print(f"pii gate: wrote {a.gitleaks_config}", file=sys.stderr)
        return 0
    hits: list[str] = []
    if a.dir:
        if not a.dir.is_dir():
            print(f"pii gate: no such folder {a.dir}", file=sys.stderr)
            return 2
        for p in sorted(a.dir.rglob("*")):
            if p.is_file():
                hits += scan_bytes(p.relative_to(a.dir).as_posix(), p.read_bytes())
        where = str(a.dir)
    else:
        for rel in tracked_files(a.root):
            p = a.root / rel
            if p.is_file():
                hits += scan_bytes(rel, p.read_bytes())
        where = "tracked tree"
    for h in hits:
        print(h)
    print(f"pii gate: {len(hits)} finding(s) in {where}", file=sys.stderr)
    return 1 if hits else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
