// Generates web/src/theme/tokens.css from the table of record (web/src/theme/themes.ts).
// The TS module is authoritative; the CSS is a build artifact — run `npm --prefix web run
// tokens` after editing themes.ts. Node >=24 strips the TS types on import (package.json
// engines pins the floor), so the token tables are read from the same module the app ships.
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const themesPath = resolve(here, "../src/theme/themes.ts");
const outPath = resolve(here, "../src/theme/tokens.css");

const { THEMES, TOKEN_KEYS, DEFAULT_THEME } = await import(pathToFileURL(themesPath).href);

function block(selector, theme) {
  const lines = [`${selector} {`, `  color-scheme: ${theme.scheme};`];
  for (const k of TOKEN_KEYS) lines.push(`  --${k}: ${theme.tokens[k]};`);
  lines.push("}");
  return lines.join("\n");
}

const def = THEMES.find((t) => t.id === DEFAULT_THEME);
const parts = [
  "/* GENERATED by scripts/emit-tokens.mjs from src/theme/themes.ts — do not hand-edit. */",
  "/* Regenerate: npm --prefix web run tokens */",
  "",
  `/* :root is the default theme (${def.label}); the pre-paint script may set data-theme. */`,
  block(":root", def),
  "",
  ...THEMES.map((t) => block(`html[data-theme="${t.id}"]`, t)),
  "",
];

writeFileSync(outPath, parts.join("\n") + "\n", "utf8");
console.log(`wrote ${outPath} (${THEMES.length} themes, ${TOKEN_KEYS.length} tokens each)`);
